# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19bhFuBlrgrmAikMjZg753PvBp_LJEHGA
"""

array_size = int(input())
array = [int(i) for i in input().split()]
element_pos = {}
for idx, element in enumerate(array):
  element_pos[element] = idx
round = 1
for i in range(1,array_size):
  if element_pos[i] > element_pos[i+1]:
    round += 1

print(round)

