# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19bhFuBlrgrmAikMjZg753PvBp_LJEHGA
"""

import sys
array_size = int(input())
array = [int(i) for i in input().split()]
max_sum = -1e18
curr_total = 0
for num in array:
  if curr_total < 0:
    curr_total = num
  else:
    curr_total += num
  if max_sum < curr_total:
    max_sum = curr_total
print(max_sum)

