# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19bhFuBlrgrmAikMjZg753PvBp_LJEHGA
"""

from collections import defaultdict
import sys
num_movies = int(input())
start_dict = defaultdict(list)
lines = sys.stdin.readlines()
for line in lines:
  start,end = line.split()
  start_dict[int(start)].append(int(end))

start_timing = sorted(start_dict.keys(),reverse = True)
prev_start_time = start_timing[0]
count = 1
for start_time in start_timing[1:]:
  curr_start_time = start_time

  for end_time in start_dict[start_time]:
    if end_time <= prev_start_time:
      prev_start_time = curr_start_time
      count += 1
      break
print(count)

