# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19bhFuBlrgrmAikMjZg753PvBp_LJEHGA
"""

array_size = int(input())
array = sorted([int(i) for i in input().split()])
size = len(array)
cost = 0
if size % 2 == 0:
  median_element1 = int((array[int(size/2)-1] + array[int(size/2)+1-1])/2)
  median_element2 = median_element1 + 1
  cost1 = 0
  cost2 = 0
  for num in array:
    cost1 += abs(num-median_element1)
    cost2 += abs(num-median_element2)
  print(min(cost1, cost1))
else:
  median_element = array[int((size+1)/2)-1]
  for num in array:
    cost += abs(num-median_element)
  print(int(cost))

