# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19bhFuBlrgrmAikMjZg753PvBp_LJEHGA
"""

from bisect import bisect_right
num_int, total = [int(i) for i in input().split()]
array = [int(i) for i in input().split()]
final_array = []
for idx,num in enumerate(array):
    final_array.append((num,idx))
sorted_final_array = sorted(final_array, key = lambda s:s[0])
found = False
if len(array) <= 1:
    print('IMPOSSIBLE')
    found = True
else:
    for num in sorted_final_array:
        idx = num[1]
        complementary = total - num[0]
        if complementary < 0:
            continue
        p = bisect_right(sorted_final_array, complementary, key = lambda s:s[0])
        if complementary == num[0]:
          if p == len(sorted_final_array):
            if sorted_final_array[p-1][0] == complementary and sorted_final_array[p-2][0] == complementary:
              print(sorted_final_array[p-1][1]+1, sorted_final_array[p-2][1]+1)
              found = True
              break
          else:
            if (sorted_final_array[p-1][0] == sorted_final_array[p][0] == complementary):
              print(sorted_final_array[p-1][1]+1, sorted_final_array[p][1]+1)
              found = True
              break
            elif (sorted_final_array[p-1][0] == sorted_final_array[p-2][0] == complementary):
              print(sorted_final_array[p-1][1]+1, sorted_final_array[p-2][1]+1)
              found = True
              break

        else:
          if sorted_final_array[p-1][0] == complementary:
              p = sorted_final_array[p-1][1]
              if p != idx:
                print(idx + 1, p+1)
                found = True
              break
if not found:
    print('IMPOSSIBLE')