# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19bhFuBlrgrmAikMjZg753PvBp_LJEHGA
"""

from bisect import bisect_right
num_cubes = int(input()) 

array = [int(i) for i in input().split()]

towers = [(array[0],array[0])]

for num in array[1:]:
    pos_in_list = bisect_right(towers,num, key = lambda s:s[1])
    if pos_in_list == len(towers):
        towers.append((num,num))
        continue
    if towers[pos_in_list][1] > num:
        base_num = towers[pos_in_list][0]
        towers[pos_in_list] = (base_num, num) 
    elif towers[pos_in_list][1] == num:
        towers.append((num,num))    
            
print(len(towers))

